ALTER TABLE SAMMENLIGNINGSGRUNNLAG RENAME COLUMN organisasjonsnummer TO arbeidsgiverreferanse;
ALTER TABLE SAMMENLIGNINGSGRUNNLAG ALTER COLUMN arbeidsgiverreferanse TYPE VARCHAR(16);

ALTER TABLE MANEDSINNTEKT ADD COLUMN beskrivelse varchar;
ALTER TABLE MANEDSINNTEKT ADD COLUMN fordel varchar;
ALTER TABLE MANEDSINNTEKT ADD COLUMN inntektstype varchar NOT NULL;